#!/usr/bin/bash
# ENVIRONMENT used in new_test15_compute_20000101-20000101.run
# Use this file to source the environment in your
# preprocessing or postprocessing scripts

module --force purge
module use $OTHERSTAGES
module --force purge

# module load Stages/2023
# module load Stages/2024
module load Stages/2025
module load GCC
module load OpenMPI
module load imkl
module load netCDF netCDF-Fortran
module load CMake
module load Python
module load Perl
module load git
module load CDO
module unload ecCodes
module load libaec FFTW cURL
module list

#export ENABLE_JUWELS_GNUOPENMPI_WORKAROUNDS='ON'
