#!/usr/bin/bash
# Use this file to source the environment in your
# preprocessing or postprocessing scripts
module --force purge

# module load Stages/2023
# module load Stages/2024
module load Stages/2025

# use GCC + openMPI
module load GCC OpenMPI
export FC=gfortran
export F77=gfortran
export MPIFC=gfortran
export FCFLAGS=-free
export CC=cc
export CXX=c++

# # use INTEL + MPI
# module load Intel ParaStationMPI
# export FC=mpifort
# export F77=mpifort
# export MPIFC=mpifort
# export FCFLAGS=-free
# export CC=mpicc
# export CXX=mpic++

# Intel oneAPI Math Kernel Library
module load imkl

# NetCDF (network Common Data Form) software libraries
module load netCDF netCDF-Fortran

# Others libraries
module load CMake
module load git

#module load Python
#module load Perl
#module load CDO
#module unload ecCodes
#module load libaec FFTW cURL
#module list