#!/bin/bash
#SBATCH --job-name=fesom2.0
#SBATCH -p mpp
#SBATCH --ntasks=288
#SBATCH --time=00:05:00
#SBATCH -o fesom2.0_%x_%j.out
#SBATCH -e fesom2.0_%x_%j.out
module load intel.compiler intel.mpi netcdf/4.4.0_intel
module load centoslibs

set -x

ulimit -s unlimited

# determine JOBID
###JOBID=`echo $SLURM_JOB_ID |cut -d"." -f1`
jobid=$(echo $SLURM_JOB_ID | cut -d"." -f1)

ln -s ../bin/fesom.x .           # cp -n ../bin/fesom.x
cp -n ../config/namelist.config  .
cp -n ../config/namelist.forcing .
cp -n ../config/namelist.oce     .
cp -n ../config/namelist.ice     .
cp -n ../config/namelist.io      .
cp -n ../config/namelist.icepack .

date
###srun --mpi=pmi2 ./fesom.x > "fesom2.0.out"
srun --mpi=pmi2 ./fesom.x > "fesom2.0_${SLURM_JOB_NAME}_${jobid}.out"
date

#qstat -f $PBS_JOBID
#export EXITSTATUS=$?
#if [ ${EXITSTATUS} -eq 0 ] || [ ${EXITSTATUS} -eq 127 ] ; then
#sbatch job_ollie
#fi
