#!/bin/bash
#SBATCH --job-name=fesom2_test_Laurent
#SBATCH -p mpp
#SBATCH --ntasks=432 
#SBATCH --time=03:00:00
#SBATCH -o slurm-out.out
#SBATCH -e slurm-err.out
module load intel.compiler intel.mpi netcdf/4.4.0_intel
module load centoslibs

set -x

ulimit -s unlimited

# determine JOBID
JOBID=`echo $SLURM_JOB_ID |cut -d"." -f1`

#ln -s ../../bin_ctl/fesom.x .           # cp -n ../bin/fesom.x
#cp -n ../../config/namelist.config  .
#cp -n ../../config/namelist.forcing .
#cp -n ../../config/namelist.oce     .
#cp -n ../../config/namelist.ice     .
#cp -n ../../config/namelist.io      .
#cp -n ../../config/namelist.icepack .

date
srun --mpi=pmi2 ./fesom.x > "fesom2.0.out"
date

#qstat -f $PBS_JOBID
#export EXITSTATUS=$?
#if [ ${EXITSTATUS} -eq 0 ] || [ ${EXITSTATUS} -eq 127 ] ; then
#sbatch job_ollie
#fi

Resultpath='//work/ollie/mseifert/fesom2_recom/fesom2_test_Laurent/'
test -e $Resultpath/fesom.1962.oce.restart.nc && exit

IsInFile=$( tail -1 fesom2.0.out | grep -c should)
if (( IsInFile > 0 )); then
# submit next #job                                                                                                                             
                                                               
 echo "submitting next job"
 cp fesom2.0.out fesom.out.done 
 sbatch job_ollie
else
 echo "something is wrong, last line of fesom.out reads"
 echo $( tail -1 fesom2.0.out)
 echo "abnormal termination of job script"
fi

