#!/bin/bash
#SBATCH --job-name=ref
#SBATCH -p shared
##SBATCH --ntasks-per-node=128
#SBATCH --ntasks=38
#SBATCH --time=00:15:00
#SBATCH -o slurm-out.out
#SBATCH -e slurm-err.out
#SBATCH -A ab0995

source /sw/etc/profile.levante
source ../env/levante.dkrz.de/shell

ulimit -s 102400

echo Submitted job: $jobid
squeue -u $USER

# determine JOBID
JOBID=`echo $SLURM_JOB_ID |cut -d"." -f1`

ln -s ../bin/fesom.x .           # cp -n ../bin/fesom.x
cp -n ../config/namelist.config  .
cp -n ../config/namelist.forcing .
cp -n ../config/namelist.oce     .
cp -n ../config/namelist.ice     .
cp -n ../config/namelist.icepack .

export OCE_NPES=36
export MIO_NPES=2

export MULTIO_SERVER_CONFIG_PATH=./
export ECKIT_DEBUG=TRUE
export MULTIO_DEBUG=TRUE

export lib_multio=/home/a/a270029/fesom2.0/lib/multio/lib/lib64/
export lib_eccodes=/sw/spack-levante/eccodes-2.21.0-3ehkbb/lib64/

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$lib_multio:$lib_eccodes

date
srun -l fesom.x > "fesom2.0.out"
date

# qstat -f $PBS_JOBID
#export EXITSTATUS=$?
#if [ ${EXITSTATUS} -eq 0 ] || [ ${EXITSTATUS} -eq 127 ] ; then
#sbatch job_mistral
#fi

