#!/bin/bash
#SBATCH --account=clidyn.p_clidyn_work # edit your account
#SBATCH --job-name=ini
#SBATCH --partition=mpp
#SBATCH --time=00:30:00
#SBATCH --qos=30min
#SBATCH --ntasks=128            # Number of tasks (MPI) tasks to be launched
#SBATCH -o fesom2_%x_%j.out
#SBATCH -e fesom2_%x_%j.out

set -x

ulimit -s unlimited

source ../env/albedo/shell

ln -s ../bin/fesom_meshpart      .
cp -n ../config/namelist.config  .
#cp -n ../config/namelist.forcing .
#cp -n ../config/namelist.oce     .
#cp -n ../config/namelist.ice     .


#___DETERMINE SLURM JOBID+OUTPUTFILE____________________________________________
jobid=$(echo $SLURM_JOB_ID | cut -d"." -f1)
fname="fesom2_${SLURM_JOB_NAME}_${jobid}.out"

#___PUT JOB IN QUEUE____________________________________________________________
date
srun --mpi=pmi2 --ntasks=1 ./fesom_meshpart >> ${fname}
date
