#!/bin/bash
#SBATCH --job-name=fesom2.0
#SBATCH --ntasks=64
#SBATCH --time=00:45:00
#SBATCH -o slurm-out.out
#SBATCH -e slurm-err.out
#SBATCH --partition=small
#SBATCH --mem=64G

# For submit scripts demanding exclusive nodes you must add the flag #SBATCH --exclusive
# https://cesga-docs.gitlab.io/ft3-user-guide/batch_examples.html


module purge
module load cesga/2020 intel/2021.3.0 impi/2021.3.0 imkl/2021.3.0 netcdf/4.8.1 netcdf-fortran/4.5.3

export FC=mpiifort CC=mpiicc CXX=mpiicpc

export NETCDF_ROOT=/opt/cesga/2020/software/MPI/intel/2021.3.0/impi/2021.3.0/netcdf/4.8.1
export NETCDF_Fortran_INCLUDE_DIR=$NETCDF_ROOT/include
export NETCDF_C_INCLUDE_DIR=$NETCDF_ROOT/include
export NETCDF_Fortran_LIBRARY=$NETCDF_ROOT/lib64/libnetcdff.so
export NETCDF_C_LIBRARY=$NETCDF_ROOT/lib64/libnetcdf.so

export NETCDF_ROOT=/opt/cesga/2020/software/MPI/intel/2021.3.0/impi/2021.3.0/netcdf-fortran/4.5.3
export NETCDF_Fortran_INCLUDE_DIR=$NETCDF_ROOT/include
export NETCDF_Fortran_LIBRARY=$NETCDF_ROOT/lib/libnetcdff.so
export NETCDF_C_INCLUDE_DIR=$NETCDF_ROOT/../netcdf/4.8.1/include
export NETCDF_C_LIBRARY=$NETCDF_ROOT/../netcdf/4.8.1/lib64/libnetcdf.so

ulimit -s unlimited


set -x
echo Submitted job: $jobid
squeue -u $USER

# determine JOBID
JOBID=`echo $SLURM_JOB_ID |cut -d"." -f1`

ln -s ../bin/fesom.x .           # cp -n ../bin/fesom.x
cp -n ../config/namelist.config  .
cp -n ../config/namelist.forcing .
cp -n ../config/namelist.oce     .
cp -n ../config/namelist.ice     .
cp -n ../config/namelist.icepack .
cp -n ../config/namelist.tra     .
cp -n ../config/namelist.io      .
cp -n ../config/namelist.cvmix   .
cp -n ../config/namelist.dyn     .

date
srun ./fesom.x > "fesom2.0.out"
date

