#!/bin/bash
#PBS -S /usr/bin/ksh
#PBS -N fesom2DYMND
#PBS -q np
###PBS -q dp
###PBS -l EC_total_tasks=144
#PBS -l EC_total_tasks=648

# optionally, specifiy that no OpenMP is used
#PBS -l EC_threads_per_task=1

#PBS -l EC_hyperthreading=0
#PBS -l EC_user_defined_priority=99
##PBS -l walltime=00:17:00
#PBS -l walltime=03:00:00

##PBS -j oe #join out and err
#PBD -n
#PBS -o /scratch/rd/natr/run_dyamond/pbs.out
#PBS -e /scratch/rd/natr/run_dyamond/pbs.err

#PBS -m abe
#PBS -M thomas.rackow@awi.de
	
#queue	suitable for	target	processors min/max			processors per node	memory limit	wall-clock	
#np	parallel	MOM+CN	1/72			not shared	72			120 GB		48 hours

path=`pwd`
echo Initial path: $path

cd /scratch/rd/natr/run_dyamond

source $HOME/fesom2/env/ecaccess.ecmwf.int/shell

# debug
set -x

# did manually
#cp fesom.2020.???.restart.nc /scratch/rd/natr/run_dyamond/.
#cp fesom.clock /scratch/rd/natr/run_dyamond/.
#cp /fwsm/lb/project/fesom2/orca025-namelists/namelists-for-ERA5-forced-runs-with-newfesom2/namelist* /scratch/rd/natr/run_dyamond/.

cp $HOME/fesom2/bin/fesom.x .
#ln -s $HOME/fesom2/bin/fesom.x . 		#../bin/fesom.x .		# cp -n ../bin/fesom.x
#cp -n $HOME/fesom2/config/namelist.config  .	#../config/namelist.config  .
#cp -n $HOME/fesom2/config/namelist.forcing .	#../config/namelist.forcing .
#cp -n $HOME/fesom2/config/namelist.oce     .	#../config/namelist.oce     .
#cp -n $HOME/fesom2/config/namelist.ice     .	#../config/namelist.ice     .

date
echo tasks_per_node, total_tasks, HT: $EC_tasks_per_node $EC_total_tasks $EC_hyperthreads
aprun -N $EC_tasks_per_node -n $EC_total_tasks -j $EC_hyperthreads ./fesom.x > "fesom2.out"
date
