#!/bin/bash
#___SET SLURM OPTIONS___________________________________________________________
#SBATCH --account=meereis.meereis    # edit your account
#SBATCH --job-name=head
#SBATCH --partition=mpp
# disable hyperthreading
#SBATCH --hint=nomultithread
#SBATCH --nodes=4                   # Number of tasks (MPI) tasks to be launched
#SBATCH --tasks-per-node 127        # using all 128CPus we exceed the maxload limit (>130) of many used nodes
#SBATCH --cpus-per-task 1
#SBATCH --time=12:00:00
#SBATCH --qos=12h

#SBATCH -o fesom2_%x_%j.out
#SBATCH -e fesom2_%x_%j.out

##SBATCH --mail-type=END
##SBATCH --mail-user=Frank.Kauker@awi.de  

module purge 
source ../env/albedo/shell
export OMP_NUM_THREADS=1
ulimit -s unlimited

# determine JOBID
JOBID=`echo $SLURM_JOB_ID |cut -d"." -f1`

ln -s ../bin/fesom.x .           # cp -n ../bin/fesom.x
cp -n ../config/namelist.config  .
cp -n ../config/namelist.forcing .
cp -n ../config/namelist.oce     .
cp -n ../config/namelist.dyn     .
cp -n ../config/namelist.tra     .
cp -n ../config/namelist.ice     .
cp -n ../config/namelist.io      .
cp -n ../config/namelist.icepack .

#___DETERMINE SLURM JOBID+OUTPUTFILE____________________________________________
jobid=$(echo $SLURM_JOB_ID | cut -d"." -f1)
fname="fesom2_${SLURM_JOB_NAME}_${jobid}.out"

#___PUT JOB IN QUEUE____________________________________________________________
date
srun --mpi=pmi2 ./fesom.x >> ${fname}
err_srun=$?
echo -e "\033[33m --> err_srun=${err_srun} \033[0m"
date

#___SETUP JOBCHAIN______________________________________________________________
if [ ${err_srun} -eq 0 ]; then
    sbatch --dependency=aftercorr:$SLURM_JOB_ID job_albedo
fi


