#!/bin/bash
#SBATCH --job-name=fesom2.0_INI
#SBATCH -p mpp
#SBATCH --ntasks=32
#SBATCH --time=12:00:00
#SBATCH -o slurm-out.out
#SBATCH -e slurm-err.out

set -x

ulimit -s unlimited

module purge
module load intel.compiler
module load intel.mpi
module load netcdf/4.4.0_intel

ln -s ../bin/fesom_ini.x         .           # cp -n ../bin/fvom_ini.x
cp -n ../config/namelist.config  .
cp -n ../config/namelist.forcing .
cp -n ../config/namelist.oce     .
cp -n ../config/namelist.ice     .


# determine JOBID
JOBID=`echo $SLURM_JOB_ID |cut -d"." -f1`

date
srun --mpi=pmi2 --ntasks=1 ./fesom_ini.x > "fvom_ini.out"
date

