#!/bin/bash
#SBATCH --job-name=fesom2.0
#SBATCH -p compute2
#SBATCH --ntasks=1
#SBATCH --time=00:15:00
#SBATCH -o slurm-out.out
#SBATCH -e slurm-err.out
#SBATCH -Aab0246 
#SBATCH --mail-type=FAIL

set -x

ulimit -s unlimited

# determine JOBID
JOBID=`echo $SLURM_JOB_ID |cut -d"." -f1`

ln -s ../bin/fesom_ini.x         .           # cp -n ../bin/fvom_ini.x
cp -n ../config/namelist.config  .
cp -n ../config/namelist.forcing .
cp -n ../config/namelist.oce     .
cp -n ../config/namelist.ice     .

date
srun --mpi=pmi2 --ntasks=1 ./fesom_ini.x > "fesom_ini.out"
date
