#!/bin/bash
#SBATCH --job-name=fesom2.0
#SBATCH -p mpp
#SBATCH --ntasks=432
#SBATCH --time=00:20:00
#SBATCH -o slurm-out.out
#SBATCH -e slurm-err.out
module load intel.compiler intel.mpi netcdf/4.4.0_intel
module load centoslibs

set -x

ulimit -s unlimited

# determine JOBID
JOBID=`echo $SLURM_JOB_ID |cut -d"." -f1`

ln -s ../bin/fesom.x .           # cp -n ../bin/fesom.x
cp  ../config/namelist.config  .
cp  ../config/namelist.forcing .
cp  ../config/namelist.oce     .
cp  ../config/namelist.ice     .
cp  ../config/namelist.io     .

date
srun --mpi=pmi2 ./fesom.x > "fesom2.0.out"
date

#qstat -f $PBS_JOBID
#export EXITSTATUS=$?
#if [ ${EXITSTATUS} -eq 0 ] || [ ${EXITSTATUS} -eq 127 ] ; then
#sbatch job_ollie
#fi
