#!/bin/bash

set -e

ulimit -s unlimited

export OMP_NUM_THREADS=1

ln -sf ../bin/fesom.x .           # cp -n ../bin/fesom.x
cp -n ../config/namelist.config  .
cp -n ../config/namelist.forcing .
cp -n ../config/namelist.oce     .
cp -n ../config/namelist.ice     .
cp -n ../config/namelist.io      .

date
time mpirun --allow-run-as-root --mca btl_vader_single_copy_mechanism none -n 2  fesom.x
date


