#!/bin/bash

ulimit -s unlimited

# determine JOBID

ln -s ../bin/fesom.x .           # cp -n ../bin/fesom.x
cp -n ../config/namelist.config  .
cp -n ../config/namelist.forcing .
cp -n ../config/namelist.oce     .
cp -n ../config/namelist.ice     .
cp -n ../config/namelist.io     .

date
mpirun --allow-run-as-root --mca btl_vader_single_copy_mechanism none -n 2  fesom.x
date


