#!/bin/bash
source ../env.sh # source this from your run script

path=`pwd`
echo Initial path: $path

mkdir -p /scratch/rd/natr/run
cd /scratch/rd/natr/run

# debug
set -x

cp -n $HOME/fesom2/bin/fesom.x . 		#../bin/fesom.x .		# ln -s ../bin/fesom.x
cp -n $HOME/fesom2/config/namelist.config  .	#../config/namelist.config  .
cp -n $HOME/fesom2/config/namelist.forcing .	#../config/namelist.forcing .
cp -n $HOME/fesom2/config/namelist.oce     .	#../config/namelist.oce     .
cp -n $HOME/fesom2/config/namelist.ice     .	#../config/namelist.ice     .

date
#aprun -N $EC_tasks_per_node -n $EC_total_tasks -j $EC_hyperthreads ./fesom.x > "fesom2.out"
#./fesom.x > "fesom2.out"
mpirun -np 4 ./fesom.x > "fesom2.out"
date
