#!/bin/bash

set -e

ulimit -s unlimited

export OMP_NUM_THREADS=1

ln -sf ../bin/fesom.x .           # cp -n ../bin/fesom.x
cp ../config/namelist.config  .
cp ../config/namelist.forcing .
cp ../config/namelist.oce     .
cp ../config/namelist.ice     .
cp ../config/namelist.io      .
cp ../config/namelist.dyn     .
date
time mpirun --allow-run-as-root --mca btl_vader_single_copy_mechanism none -n 4  fesom.x
date


