#!/bin/bash
#SBATCH --job-name=fesom2.0
#SBATCH -p mpp
#SBATCH --ntasks=72
#SBATCH --time=1:00:00

set -x

ulimit -s 1000000

module purge
module load intel.compiler
module load intel.mpi
module load netcdf/4.4.0_intel

# determine JOBID
JOBID=`echo $PBS_JOBID |cut -d"." -f1`

#export I_MPI_FABRICS=shm:tmi

cd /home/ollie/dsidoren/fesom2.0/bin
date
srun --mpi=pmi2 --ntasks=72 ./fvom.x > fvom.out
date
qstat -f $PBS_JOBID

#export EXITSTATUS=$?
#if [ ${EXITSTATUS} -eq 0 ] || [ ${EXITSTATUS} -eq 127 ] ; then
#sbatch job.ll_ollie
#fi

