
ASSOCIATE ( &
nod2D              => mesh%nod2D, &
elem2D             => mesh%elem2D, &
edge2D             => mesh%edge2D, &
edge2D_in          => mesh%edge2D_in, &
ocean_area         => mesh%ocean_area, &
nl                 => mesh%nl, &
nn_size            => mesh%nn_size, &
ocean_areawithcav  => mesh%ocean_areawithcav, &
coord_nod2D                  => mesh%coord_nod2D(1:2,1:myDim_nod2D+eDim_nod2D), &
geo_coord_nod2D              => mesh%geo_coord_nod2D(1:2,1:myDim_nod2D+eDim_nod2D), &
elem2D_nodes => mesh%elem2D_nodes(1:3, 1:myDim_elem2D+eDim_elem2D+eXDim_elem2D), &
edges                      => mesh%edges(1:2,1:myDim_edge2D+eDim_edge2D), &
edge_tri                   => mesh%edge_tri(1:2,1:myDim_edge2D+eDim_edge2D), &
elem_edges                             => mesh%elem_edges(1:3,1:myDim_elem2D), &
elem_area         => mesh%elem_area(1:myDim_elem2D+eDim_elem2D+eXDim_elem2D), &
edge_dxdy                  => mesh%edge_dxdy(1:2,1:myDim_edge2D+eDim_edge2D), &
edge_cross_dxdy            => mesh%edge_cross_dxdy(1:4,1:myDim_edge2D+eDim_edge2D), &
elem_cos          => mesh%elem_cos(1:myDim_elem2D+eDim_elem2D+eXDim_elem2D), &
metric_factor     => mesh%metric_factor(1:myDim_elem2D+eDim_elem2D+eXDim_elem2D), &
elem_neighbors                       => mesh%elem_neighbors(1:3,1:myDim_elem2D), &
nod_in_elem2D      => mesh%nod_in_elem2D, &   ! (maxval(rmax),myDim_nod2D+eDim_nod2D)
x_corners          => mesh%x_corners, &   ! (myDim_nod2D, maxval(rmax))
y_corners          => mesh%y_corners, &   ! (myDim_nod2D, maxval(rmax))
nod_in_elem2D_num                => mesh%nod_in_elem2D_num(1:myDim_nod2D+eDim_nod2D), &
depth                            => mesh%depth(1:myDim_nod2D+eDim_nod2D), &
gradient_vec                           => mesh%gradient_vec(1:6,1:myDim_elem2D), &
gradient_sca                           => mesh%gradient_sca(1:6,1:myDim_elem2D), &
bc_index_nod2D                   => mesh%bc_index_nod2D(1:myDim_nod2D+eDim_nod2D), &
zbar                                            => mesh%zbar(1:mesh%nl), &
Z                                             => mesh%Z(1:mesh%nl-1), &
elem_depth         => mesh%elem_depth, &      ! never used, not even allocated
nlevels           => mesh%nlevels(1:myDim_elem2D+eDim_elem2D+eXDim_elem2D), &
nlevels_nod2D                    => mesh%nlevels_nod2D(1:myDim_nod2D+eDim_nod2D), &
nlevels_nod2D_min                => mesh%nlevels_nod2D_min(1:myDim_nod2D+eDim_nod2D), &
area                   => mesh%area(1:mesh%nl,1:myDim_nod2d+eDim_nod2D), &
areasvol               => mesh%areasvol(1:mesh%nl,1:myDim_nod2d+eDim_nod2D), &
area_inv               => mesh%area_inv(1:mesh%nl,1:myDim_nod2d+eDim_nod2D), &
areasvol_inv           => mesh%areasvol_inv(1:mesh%nl,1:myDim_nod2d+eDim_nod2D), &
mesh_resolution                  => mesh%mesh_resolution(1:myDim_nod2d+eDim_nod2D), &
ssh_stiff                                                  => mesh%ssh_stiff, &
lump2d_north                                => mesh%lump2d_north(1:myDim_nod2d), &
lump2d_south                                => mesh%lump2d_south(1:myDim_nod2d), &
cavity_flag_n                    => mesh%cavity_flag_n(1:myDim_nod2D+eDim_nod2D), &
cavity_flag_e     => mesh%cavity_flag_e(1:myDim_elem2D+eDim_elem2D+eXDim_elem2D), &
!!$cavity_lev_nod2D(1:myDim_nod2D+eDim_nod2D)                 => mesh%cavity_lev_nod2D, &
!!$cavity_lev_elem2D(1:myDim_elem2D+eDim_elem2D+eXDim_elem2D) => mesh%cavity_lev_elem2D, &
cavity_depth                     => mesh%cavity_depth(1:myDim_nod2D+eDim_nod2D), &
ulevels           => mesh%ulevels(1:myDim_elem2D+eDim_elem2D+eXDim_elem2D), &
ulevels_nod2D                    => mesh%ulevels_nod2D(1:myDim_nod2D+eDim_nod2D), &
ulevels_nod2D_max                => mesh%ulevels_nod2D_max(1:myDim_nod2D+eDim_nod2D), &
nn_num                                      => mesh%nn_num(1:myDim_nod2D), &
nn_pos                      => mesh%nn_pos(1:mesh%nn_size, 1:myDim_nod2D),  &
hnode               => mesh%hnode(1:mesh%nl-1, 1:myDim_nod2D+eDim_nod2D), &
hnode_new           => mesh%hnode_new(1:mesh%nl-1, 1:myDim_nod2D+eDim_nod2D), &
zbar_3d_n             => mesh%zbar_3d_n(1:mesh%nl, 1:myDim_nod2D+eDim_nod2D), &
Z_3d_n              => mesh%Z_3d_n(1:mesh%nl-1, 1:myDim_nod2D+eDim_nod2D), &
helem                         => mesh%helem(1:mesh%nl-1, 1:myDim_elem2D), &
bottom_elem_thickness                      => mesh%bottom_elem_thickness(1:myDim_elem2D), &
bottom_node_thickness            => mesh%bottom_node_thickness(1:myDim_nod2D+eDim_nod2D), &
dhe                                        => mesh%dhe(1:myDim_elem2D), &
hbar                             => mesh%hbar(1:myDim_nod2D+eDim_nod2D), &
hbar_old                         => mesh%hbar_old(1:myDim_nod2D+eDim_nod2D), &
!zbar_n(1:mesh%nl)                                          => mesh%zbar_n, &
!Z_n(1:mesh%nl-1)                                           => mesh%Z_n, &
zbar_n_bot                       => mesh%zbar_n_bot(1:myDim_nod2D+eDim_nod2D), &
zbar_e_bot                     => mesh%zbar_e_bot(1:myDim_elem2D+eDim_elem2D), &
zbar_n_srf                       => mesh%zbar_n_srf(1:myDim_nod2D+eDim_nod2D), &
zbar_e_srf                     => mesh%zbar_e_srf(1:myDim_elem2D+eDim_elem2D)   )
