
# Compiler and Linker
CC = gcc 
LD = $(CC)

# Optimization specs for compiler
OPT = -O2 

# What archiving to use
# Do not use option "r" - util.o comes twice from GKlib and libmetis!
# Instead, the Makefiles makes sure to clean any old lib first.
AR = ar qv

# What to use for indexing the archive
RANLIB = ranlib
