# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '00 14 * * *'
  workflow_dispatch:

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - run: |
        echo "$(date) :: The job was manually dispatched, or automatically triggered by a schedule. If you are seeing this message, the schedule is working correctly."
    - uses: actions/stale@v5
      with:
        operations-per-run: 1000
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-issue-stale: 730
        days-before-pr-stale: 730
        days-before-issue-close: 30
        days-before-pr-close: -1
        stale-issue-message: 'This issue has been inactive for two years. It will now be marked as stale and closed after 30 days of further inactivity. Please add a comment to reset this automatic closing of this issue or close it if solved.'
        stale-pr-message: 'This PR has been inactive for two years. It will now be marked as stale. Please close this PR if no longer needed.'
        stale-issue-label: 'Stale'
        stale-pr-label: 'Stale'
        close-issue-label: 'Closed by github-actions'
        exempt-issue-labels: enhancement, feature request
        exempt-pr-labels: enhancement, feature request
        exempt-issue-milestones: '*'

