
name: "FESOM2: Channel"
# Controls when the action will run. Triggers the workflow on push or pull request. 
on:
  workflow_dispatch: {}
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  general_test:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: ghcr.io/fesom/fesom2_docker:fesom2_test_refactoring-master

    # Service containers to run with `gfortran_ubuntu`
    steps:
    # NK: this changes working directory to fesom2
    - uses: actions/checkout@v2

    - name: Git safe directory
      run: |
        git config --global --add safe.directory ${PWD}

    - name: Compile model (binary)
      run: |
        ./configure.sh ubuntu

    - name: Create channel test run
      run: |
        mkrun souf test_souf -m docker

    - name: FESOM2 channel test run
      run: |    
        cd work_souf
        chmod +x job_docker_new
        ./job_docker_new

    - name: Check channel  results
      run: |
        cd work_souf
        fcheck .    