name: "FESOM2: Icebergs"

# Controls when the action will run. Triggers the workflow on push or pull request.

on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  general_test:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: ghcr.io/fesom/fesom2_docker:fesom2_test_refactoring-master

    # Service containers to run with `gfortran_ubuntu`
    steps:
      # NK: this changes working directory to fesom2
      - uses: actions/checkout@v2

      - name: Git safe directory
        run: |
          git config --global --add safe.directory ${PWD}

      - name: Compile model (binary)
        run: |
          ./configure.sh ubuntu

      - name: Create iceberg test run
        run: |
          mkrun iceberg test_pi_icebergs -m docker
          # Add iceberg files
          cp test/input/icebergs/icb_height.dat work_iceberg/
          cp test/input/icebergs/icb_latitude.dat work_iceberg/
          cp test/input/icebergs/icb_length.dat work_iceberg/
          cp test/input/icebergs/icb_longitude.dat work_iceberg/
          cp test/input/icebergs/icb_scaling.dat work_iceberg/

      - name: FESOM2 iceberg test run
        run: |
          cd work_iceberg
          ls -ratl
          cat namelist.config
          chmod +x job_docker_new
          ./job_docker_new
      - name: Check iceberg results
        run: |-
          cd work_iceberg
          fcheck .