name: Run CICD on Lumi (using .gitlab-ci.yml)

on: push
  branches:
    - refactoring
    - lumi_gpu_evatali

jobs:
  gitlabsync:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "Gitlab mirror and CI"
        uses: "tiggi/gitlab-mirror-and-ci-action@tiggi/fixes"
        with:
          args: "https://gitlab.com/lumi-cicd/fesom2.git"
        env:
          FOLLOW_TAGS: "true"
          FORCE_PUSH: "true"
          GITLAB_HOSTNAME: "gitlab.com"
          GITLAB_USERNAME: "tiggi"
          GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
          GITLAB_PROJECT_ID: "51374059"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
