name: "FESOM2: Mesh Partitioner"

# Controls when the action will run. Triggers the workflow on push or pull request.

on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  general_test:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: ghcr.io/fesom/fesom2_docker:fesom2_test_refactoring-master

    # Service containers to run with `gfortran_ubuntu`
    steps:
      # NK: this changes working directory to fesom2
      - uses: actions/checkout@v2

      - name: Git safe directory
        run: |
          git config --global --add safe.directory ${PWD}

      - name: Check partitioner compilation
        run: |
          cd mesh_part
          bash -l configure.sh ubuntu

      - name: Run partitioner
        run: |
          cd work_pi
          cp ../bin/fesom_ini.x .
          ./fesom_ini.x